In [12]:
import pandas as pd
import random
from pathlib import Path

In [14]:
omics = ['dna_methylation', 'gene_expression', 'protein_expression']
files = [f"../data/toy_dataset/{omic}_unpaired_x_train.tab" for omic in omics]
num_samples = 500

samples = random.sample(list(range(len(df))), num_samples)


for file in files:
    file = Path(file)
    file2 = Path(str(file).replace('_x_', '_y_'))
    
    filename, ext = file.stem, file.suffix
    filename2 = Path(str(filename).replace('_x_', '_y_'))

    save_dir = Path('./dataset')
    save_dir.mkdir(parents=True, exist_ok=True)
    
    df = pd.read_csv(file, sep='\t', index_col=0, header=0)
    df_filtered = df.iloc[samples]

    df2 = pd.read_csv(file2, sep='\t', index_col=0, header=0)
    df_filtered2 = df2.iloc[samples]

    df_filtered2 = df_filtered2.rename(columns={'cluster.id': 'label'}, inplace=False)  ###

    df_filtered = df_filtered.sort_index(key=lambda x: x.map(lambda item: int(item.replace('subject', ''))))
    df_filtered2 = df_filtered2.sort_index(key=lambda x: x.map(lambda item: int(item.replace('subject', ''))))
    
    df_filtered.to_csv(f"{save_dir}/{filename}{ext}", sep='\t', index=True)
    df_filtered2.to_csv(f"{save_dir}/{filename2}{ext}", sep='\t', index=True)

In [94]:
omics = ['dna_methylation', 'gene_expression', 'protein_expression']
files = [f"./dataset/{omic}_unpaired_x_train.tab" for omic in omics]
for file in files:
    file = Path(file)
    filename, ext = file.stem, file.suffix

    df = pd.read_csv(file, sep='\t', index_col=0, header=0)
    display(df)

,cg20139214,cg10999429,cg23640701,cg02956093,cg08711674,cg09842540,cg11739626,cg19073614,cg01894895,cg01086868,...,cg16579354,cg21404906,cg01442799,cg26369667,cg00650876,cg07064406,cg22799917,cg11816577,cg25299176,cg07981588
subject2200,0.024958,0.008284,0.496897,0.110515,0.700993,0.009651,0.461020,0.023710,0.844113,0.338865,...,0.038183,0.067267,0.030979,0.006453,0.014243,0.893236,0.016827,0.264123,0.296693,0.033443
subject659,0.023207,0.014580,0.401700,0.358504,0.696292,0.047200,0.373128,0.020111,0.864058,0.080152,...,0.025837,0.058393,0.022090,0.002581,0.006972,0.901284,0.076797,0.037205,0.103955,0.016494
subject212,0.024877,0.030505,0.390312,0.087616,0.261166,0.005545,0.461912,0.018372,0.932470,0.297204,...,0.030533,0.024179,0.131731,0.046457,0.053119,0.984491,0.108626,0.043774,0.092130,0.069613
subject2401,0.036302,0.160119,0.703541,0.553391,0.484743,0.119818,0.664894,0.025720,0.854890,0.290249,...,0.067865,0.303133,0.041277,0.013540,0.015758,0.981286,0.197845,0.100510,0.190514,0.039852
subject3491,0.047627,0.021205,0.471559,0.127612,0.333467,0.022038,0.441054,0.047159,0.785214,0.287757,...,0.049988,0.095358,0.294057,0.148713,0.187257,0.981333,0.183304,0.046059,0.042633,0.087412
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
subject847,0.029670,0.013658,0.232981,0.107886,0.657619,0.011329,0.527503,0.020381,0.839759,0.117681,...,0.026338,0.074559,0.033895,0.003013,0.003011,0.900800,0.012154,0.294719,0.229608,0.013617
subject813,0.052619,0.047029,0.645151,0.104231,0.772130,0.245421,0.685840,0.083700,0.794657,0.505653,...,0.310090,0.161890,0.069526,0.051427,0.034332,0.876196,0.053993,0.448858,0.636146,0.061419
subject1741,0.013599,0.093662,0.701501,0.441900,0.275944,0.027969,0.529022,0.010375,0.858571,0.334406,...,0.024191,0.133986,0.020534,0.002557,0.005098,0.986666,0.054963,0.053015,0.036641,0.017959
subject376,0.025021,0.081234,0.457686,0.116577,0.832730,0.016237,0.399653,0.033543,0.872725,0.104945,...,0.045750,0.038579,0.041116,0.014027,0.018586,0.917049,0.019024,0.360104,0.388088,0.039396
subject1385,0.022203,0.024183,0.541163,0.108031,0.475460,0.007915,0.583167,0.011216,0.833435,0.267785,...,0.027305,0.030846,0.117826,0.015105,0.054828,0.986803,0.083891,0.054234,0.023264,0.042097

,ACACA,ACVRL1,AKT1,AKT1S1,ANXA1,AR,ARAF,ASNS,ATM,BAD,...,VHL,WWTR1,XBP1,XRCC1,XRCC5,YAP1,YBX1,YWHAB,YWHAE,YWHAZ
subject4408,-0.679322,1.741545,-0.499305,-0.428517,0.337339,2.888834,-0.542696,1.290763,-1.463119,2.437465,...,0.023370,-0.734757,0.012604,0.773302,0.676959,3.568755,1.361070,2.235796,1.453285,0.839950
subject5849,-0.038723,0.991740,1.172342,2.089382,0.792169,3.459838,1.123924,1.986157,-0.454942,0.884837,...,1.682495,0.074273,-1.334078,-0.007741,1.046679,-0.137163,-0.404692,1.277286,1.380692,-0.655317
subject6025,-0.662495,0.903826,-0.099994,1.636436,1.198067,5.182750,1.737397,-1.852480,2.039829,2.433452,...,3.028531,3.578399,-1.541107,-0.501152,2.133633,1.112608,0.741450,0.338427,2.978020,0.807247
subject5382,-1.078364,1.149518,-0.490567,1.206611,0.650383,3.161000,-1.076325,-1.050324,2.654555,0.247754,...,2.742862,0.077589,1.550945,2.468649,0.452185,1.694646,-0.234307,-0.295926,1.780785,0.563320
subject6273,-0.719301,3.575293,1.637528,1.241170,-1.043399,0.423504,0.999764,0.879988,1.441398,0.759447,...,2.312264,0.880367,1.568097,2.695565,2.406592,1.684195,-0.551086,2.171235,1.302645,0.491615
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
subject5962,-0.887599,1.237481,-1.162408,-0.420926,-0.011199,3.756054,-0.524525,1.247115,-0.651327,2.215178,...,0.699061,0.180401,-2.221891,1.880306,0.198271,3.610416,2.871233,1.469629,0.072640,1.506967
subject6454,0.098053,1.906452,0.535509,1.410441,0.115867,6.582521,-0.647120,-1.803707,2.461583,0.774004,...,2.424901,1.582462,0.793708,1.773038,-0.280166,1.109985,0.698639,0.491945,3.101477,0.483855
subject6780,-0.476960,1.727225,0.741621,1.439332,-0.974852,2.171830,0.630918,0.920919,-0.055378,0.437972,...,1.630943,-0.657587,0.166254,0.311252,0.642885,1.396410,-0.453201,2.204441,0.840950,1.297815
subject6165,-0.690121,1.458165,-0.810772,1.296944,0.212274,2.193461,1.101864,-1.518793,1.446691,3.246952,...,1.690331,1.771894,-0.244408,-0.230885,3.061601,0.627219,-0.041078,0.498831,2.190269,1.132676
subject7123,-1.008701,1.902726,-1.578805,0.736290,-0.760343,6.320294,1.449613,-0.992792,1.942927,3.036686,...,1.516713,2.271182,-1.925316,1.935925,2.643665,2.236876,0.314114,0.435417,2.679451,0.836422

,ACC1,ACC_pS79,ACVRL1,Akt_pS473,PRAS40_pT246,Annexin.1,AR,A.Raf_pS299,ASNS,ATM,...,XBP1,XRCC1,Ku80,YAP,YAP_pS127,YB.1,YB.1_pS102,14.3.3_beta,14.3.3_epsilon,14.3.3_zeta
subject10887,0.511379,0.123961,0.203618,-0.058559,-0.056782,0.119827,3.525475,0.017353,1.830598,-0.054042,...,-0.313991,-0.039334,0.268388,2.547494,1.998831,1.569554,2.121581,2.098886,0.295022,0.407021
subject8348,-0.490697,-0.314771,0.062840,0.041600,0.056453,0.904371,2.990190,-0.202739,1.633512,-0.125177,...,-0.122861,0.062562,0.256424,2.631975,2.368628,1.440657,1.830762,2.082212,-0.197048,0.230191
subject9076,0.802417,0.382969,2.483019,1.535587,1.651181,0.060823,1.510832,1.768003,1.838982,2.111142,...,2.376437,1.908895,2.339788,0.198157,-0.420191,-0.272031,0.073604,2.557401,0.109829,-0.009237
subject8328,-1.197070,-1.063574,0.196520,0.011425,0.247910,1.383684,2.832379,0.016808,-0.390080,0.825039,...,-0.066354,-0.340666,-0.033806,2.271270,1.923139,1.497647,2.313871,2.220177,0.095175,0.414303
subject9113,-1.163022,-0.808124,0.328451,0.097126,2.041851,-0.447928,3.322628,0.482776,-1.339477,0.714736,...,1.581744,1.344654,0.005328,0.721360,0.697954,-0.361926,0.358266,0.013312,1.896067,0.742034
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
subject10149,0.355001,0.258655,1.970299,2.398701,2.052760,-1.276753,1.693690,2.372712,1.682576,1.575635,...,1.690330,1.830606,2.035496,-0.275440,-0.169834,-0.505855,0.372770,1.928428,-0.040472,0.184800
subject10265,-0.126029,0.096604,0.058881,0.770298,2.014177,-0.447005,3.203171,0.073492,-0.432876,2.373621,...,1.753787,2.024066,-0.331883,0.279004,0.579725,-0.095555,-0.115374,-0.132059,1.922116,1.183440
subject11499,-0.844315,-0.996398,-0.284149,3.047146,2.161086,-0.210802,2.897339,1.928232,0.069719,-1.021843,...,0.420318,0.097545,-0.396009,0.293832,-0.019482,0.726012,0.260090,2.077078,-0.112168,0.745723
subject8605,0.127754,0.512083,0.358738,0.551396,1.803315,-1.068596,3.306175,1.648753,1.977419,0.115302,...,0.328364,-0.463872,-0.245648,0.175923,0.021151,0.431717,-0.233226,2.052635,0.315644,0.492493
subject9378,-1.045102,-0.921550,0.213469,-0.634371,2.167200,-0.655018,3.982074,-0.176507,0.075430,1.929567,...,1.812398,1.902867,-0.657421,1.002154,1.381928,0.339521,0.176884,0.121761,2.138153,-0.259365

In [15]:
omics = ['dna_methylation', 'gene_expression', 'protein_expression']
files = [f"./dataset/{omic}_unpaired_x_test.tab" for omic in omics]
for file in files:
    file = Path(file)
    file2 = Path(str(file).replace('_x_', '_y_'))
    
    filename, ext = file.stem, file.suffix
    filename2 = Path(str(filename).replace('_x_', '_y_'))

    df = pd.read_csv(file, sep='\t', index_col=0, header=0)
    df2 = pd.read_csv(file2, sep='\t', index_col=0, header=0)
    # display(df.head())
    # display(df2.head())
    print(all(df.index == df2.index))

True
True
True

In [8]:
df.index.map(lambda x: x.replace('subject', ''))

Index(['7901', '9760', '8087', '10117', '10284', '9302', '8811', '11074',
       '8331', '9138', '8872', '8357', '8906', '7924', '9019', '10691', '8186',
       '11263', '10406', '10539', '8321', '9731', '9946', '8871', '8905',
       '10216', '8057', '8539', '10844', '8538', '9991', '8940', '10317',
       '10085', '7735', '8748', '9283', '10497', '11396', '9644', '10760',
       '10350', '11017', '8050', '9238', '10938', '9487', '9997', '9518',
       '8068'],
      dtype='object')

## Example 1

In [78]:
import pandas as pd
import torch
from torch.utils.data import Dataset

class ModalityDataset(Dataset):

    def __init__(self, data, labels, include_ids: bool, transform=None):
        self.df = torch.tensor(data.values, dtype=torch.float32)
        self.labels = labels
        self.include_ids = include_ids
        self.transform = transform

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        # Make sure both dataframes are sorted in the same way
        x = self.df[idx,:]
        y = self.labels.iloc[idx]['label'].item()

        if self.transform:
            x = self.transform(x)

        # Useful when generating reports
        if self.include_ids:
            s = self.labels.index[idx]
            return x, y, s

        return x, y

def load_data(dataset_name: str, split: str, data_dir: str = '.'):
    if split not in ['train', 'test']:
        raise ValueError(f"Invalid split '{split}'. Valid options are 'train' or 'test'.")

    modalities = ['dna_methylation', 'gene_expression']
    data = []
    for modality in modalities:
        x_df = pd.read_csv(f"{data_dir}/{dataset_name}/{modality}_unpaired_x_{split}.tab", sep='\t', index_col=0, header=0)
        y_df = pd.read_csv(f"{data_dir}/{dataset_name}/{modality}_unpaired_y_{split}.tab", sep='\t', index_col=0, header=0)
        data.append((x_df, y_df))
    return data

def get_dataset(
    dataset_name: str,
    split: str,
    data_dir: str = '.',
    include_ids: bool = False
) -> list[ModalityDataset]:    
    # Load the dataset
    data = load_data(
        dataset_name=dataset_name,
        split=split
    )

    # Generate the Dataset
    dataset = [ModalityDataset(x, y, include_ids=include_ids) for x,y in data]

    return dataset

In [83]:
dataset = get_dataset(dataset_name='toy_dataset', split='train', include_ids=False)

## Example 2

In [21]:
from pathlib import Path

import torch
import pandas as pd
import numpy as np
from torch.utils.data import Dataset
from sklearn.preprocessing import StandardScaler

class ModalityDataset(Dataset):

    def __init__(self, data_path, labels_path, include_ids=False, transform=None):
        self.data = pd.read_csv(data_path, sep='\t', index_col=0)
        self.labels = pd.read_csv(labels_path, sep='\t', index_col=0)
        self.include_ids = include_ids
        self.transform = transform

        # Standardize the data
        self.scaler = StandardScaler()
        normalized_data = self.scaler.fit_transform(self.data)
        self.data = pd.DataFrame(normalized_data, columns=self.data.columns, index=self.data.index)
        
        # Adjust labels to zero-indexed
        self.labels['label'] = self.labels['label'] - 1
        
        # Convert to numpy for faster indexing
        self.data_values = self.data.values.astype(np.float32)
        
    def __len__(self):
        return len(self.data)
    
    def __getitem__(self, idx):
        x = torch.from_numpy(self.data_values[idx])
        y = torch.tensor(self.labels.iloc[idx]['label'], dtype=torch.long)
        
        if self.transform:
            x = self.transform(x)
            
        if self.include_ids:
            return x, y, self.data.index[idx]
        return x, y

def get_datasets(dataset_name: str, split: str, include_ids=False, data_dir='.'):
    if split not in ['train', 'test']:
        raise ValueError(f"Invalid split '{split}'. Valid options are 'train' or 'test'.")

    data_dir = Path(data_dir) / dataset_name
    modalities = ['dna_methylation', 'gene_expression']
    
    datasets = []
    for modality in modalities:
        data_path = data_dir / f"{modality}_unpaired_x_{split}.tab"
        labels_path = data_dir / f"{modality}_unpaired_y_{split}.tab"
        datasets.append(ModalityDataset(data_path, labels_path, include_ids))
    
    return datasets

In [22]:
datasets = get_datasets(dataset_name='toy_dataset', split='train', include_ids=True, data_dir='../data')

In [23]:
datasets[0][2]

(tensor([-0.3696, -0.4937,  0.5731, -0.8768,  0.8528, -0.0905, -0.2054, -0.7904,
          0.9660, -0.0688, -0.4216,  0.0218,  0.2540,  1.0420, -0.4996, -0.6833,
          1.7106, -0.6863,  0.0173, -0.2897, -0.6839,  0.7215, -0.8478, -0.6181,
          1.5369, -0.5485, -0.5050, -0.4028, -0.7083, -0.6272,  1.8112,  1.4654,
         -0.5717, -1.0966, -1.5981,  0.4851,  0.4843, -0.6492, -1.0146,  0.8982,
         -1.0911, -0.6855, -0.6297, -0.7695, -0.8137, -0.8820, -0.6150, -0.5416,
         -0.7633, -0.8435, -0.9937, -0.6914, -0.6586,  0.6213, -0.6349, -0.8419,
         -0.9131,  1.2123,  1.2288, -0.5704, -0.6580,  0.3351,  2.2306, -0.5744,
         -1.2285, -0.6119, -0.5440, -0.5185, -0.5095,  0.9949,  1.3270, -0.1865,
          1.7189, -0.0611, -0.8319, -0.5110, -1.4164,  0.0429,  0.6845, -0.6621,
         -0.5730, -0.3069, -0.5283, -1.0229, -0.6888, -2.1990, -0.0593,  0.2666,
         -0.4432, -1.0523, -1.1273, -0.6328,  0.7685, -0.3601, -0.5825, -0.6609,
          0.0933, -0.4554, -0.4604, -0.5191,  1.2759, -0.3733, -0.4121, -0.9387,
         -0.3261, -0.7345, -0.9014, -0.8243, -0.6294, -0.7740, -0.4879, -0.8606,
         -0.4863,  0.1263, -0.6812, -0.4993, -0.5228,  0.4447, -0.9732, -0.5884,
         -0.6448, -0.3489, -0.3776, -0.4669,  1.4360, -2.1108,  0.2853, -0.1473,
         -0.5390, -0.4552, -0.4816,  0.2501, -0.1950, -0.3900, -2.3965, -0.1580,
         -2.0614, -1.1075,  0.4904, -0.7325, -0.6523, -0.6117,  0.0218,  0.0122,
         -0.5779, -0.6174, -0.5312, -0.4906, -0.5667, -0.5334, -0.9175, -0.6195,
         -0.6635, -0.8734, -0.4133,  0.3627, -1.0426, -0.0333, -0.7870, -0.7183,
          0.3132, -0.5530, -0.3607,  0.9439, -0.4979, -0.5721, -0.1961,  0.5807,
         -1.2001, -0.7470, -0.3902,  1.4713, -0.6345, -0.2552,  0.4869, -0.3949,
         -0.1729, -0.0146, -0.5698,  0.0415,  0.6759,  0.3913,  1.0107, -0.5997,
         -0.7854, -0.7325, -0.5911, -0.6499, -0.4911,  0.8979, -0.9400, -0.5027,
         -0.7008, -0.2262, -0.9871, -0.5354, -0.8183, -0.6317, -0.8103, -0.6780,
         -0.8066, -0.9413,  1.0240, -0.1380,  0.5431, -0.4884, -0.6165, -0.7960,
         -0.6439, -0.5235, -0.9712, -0.6804, -0.6267, -0.4592, -0.4928, -0.6779,
         -0.6607, -0.6284, -0.6166, -0.7830, -0.6858, -0.6280, -0.5044, -0.6197,
          1.3229, -0.7958, -0.6213, -0.7582,  0.6075, -0.2140, -0.3736, -0.4762,
         -0.4622, -0.6361, -0.4773,  0.4157, -0.5483, -0.9438,  0.6651, -0.8688,
          0.0747, -0.2006, -0.0241,  0.6428, -2.5521, -0.3246, -0.6486, -0.8073,
         -0.2236, -0.9396, -0.9347, -0.4710, -0.7620, -0.6372, -0.7916, -0.6214,
         -0.6238,  0.1949, -0.6502, -1.0054, -0.6617, -0.3997, -0.8213, -0.9664,
         -0.5713,  1.0446, -0.5943, -0.5422, -0.6154,  0.5168,  0.1088,  0.0869,
          0.8295, -1.3571, -0.7596, -1.6964,  0.1053,  1.1266, -0.9393,  0.4522,
          0.3182,  1.4989, -0.5571,  1.1325,  0.5697, -1.1677,  1.0433,  0.4645,
          1.3638, -1.0400, -0.2715,  0.7143, -1.8628, -0.2511, -0.3212, -0.6820,
          0.4401, -0.4821,  0.9766, -0.6709,  0.7554, -0.8110,  0.2039, -0.4986,
         -1.5194, -0.5589, -0.4919, -0.6631,  0.7656, -0.7395, -1.1906,  1.3644,
         -1.5210, -0.5279,  0.2041,  0.1342,  0.4948, -0.9427,  0.5184, -0.7808,
          0.3302, -0.0540,  1.9257, -0.7319, -0.5652, -0.5969, -0.8045, -0.7986,
          1.5053, -0.3661, -1.2580, -0.6178, -0.6802, -0.7153, -0.3726, -0.4375,
         -0.5485, -0.5924, -0.2005, -0.9764, -0.5572,  1.5929,  1.3104, -0.6559,
         -0.5639, -1.1189, -1.1481, -0.4838, -1.4322,  1.3369, -0.0444,  0.4205,
         -0.8601, -0.6041, -1.2375, -0.7042, -0.3725,  1.6413, -0.6074, -0.6918,
         -0.4738, -0.5643, -0.8396, -1.1210,  0.7095,  1.5673,  0.1790]),
 tensor(4),
 'subject20')